### PR TITLE
A number of icon additions and updates.

### PR DESCRIPTION
**Pull request by Faire-Fuzzy**
Added a 3 outfits in the Uniform.dmi, a HEV suit with matching helmet, an update to the panthers (gave them more detail and made the females....female), updated the slimes ( killed the stupid base sprite hair), and added another race( just really added it to add it, i'd love to see it in game, but do whatever you like with it.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
slimes are already fixed in my PR

**Comment by Faire-Fuzzy** [comment]
Oh....well XP

**Comment by Faire-Fuzzy** [comment]
I'm really new to this, desert plan, that doesn't really affect anything right?

**Comment by Faire-Fuzzy** [comment]
t*

**Comment by Faire-Fuzzy** [comment]
Here's more random stuff, mostly ripped thing from baycode, hippie, and a rare few from /vg/

**Comment by Faire-Fuzzy** [comment]
Slimes have been dealt with, hope that fixes things.

**Pull request closed without merging**
