### PR TITLE
discord bot [!!!DO NOT MERGE!!!]

### PR DESCRIPTION
**Pull request by LetterJay**
initial base.

### CODE REVIEW

**Comment by LetterJay** [comment]
dis gone b gud

**Comment by TalkingCactus** [comment]
bot for 5th port
6th will be out next week
rip

**Comment by LetterJay** [comment]
there's no difference between the two. unless 6th has all the json support.

**Comment by TalkingCactus** [comment]
6th uses json for tgui, so i guess it does

**Comment by LetterJay** [comment]
moving to 6th.

**Pull request closed without merging**
