### PR TITLE
FUCKING IMPORTANT!!!

### PR DESCRIPTION
**Pull request by Verkister**
-Fixed severe issues with borg mounted sleeper.
 *Fixed being unable to heal people with <25 health.
 *Fixed missing distance limit allowing remotely nabbing up people.
 *Added a double check to decrease the chance of functionality loss after repeated ejections.
-Added Boop module and crew monitor to MH equipment.
-Made one little frame tweak to smooth the MH walk anim.
-Nerfed the tongue cleaning just a little bit further.
-REVERTED THE FUCKED UP RACE AND TAIL SPRITES. WHAT THE FUCK IS YOUR DAMAGE???
-Your utterly disasterous sprite file didn't even have ursines or anything. Being like so many commits behind the one you overwrote with it.

### CODE REVIEW

**Comment by Verkister** [comment]
# MERGE THIS SHIT! FUCKING FORCE IT!

**Comment by Verkister** [comment]
So yeah, it's conflicting because of the sprite file disaster that shouldn't have been merge compatible in the first place!

**Comment by Verkister** [comment]
So yeah, you guys not checking the sprite file was entirely "dry your cat in a microwave" idiotic and you should NOT be making me feel "good" about my mistakes being slightly smaller.

**Comment by LetterJay** [comment]
Way too much fun to be contained.

**Pull request merged**
